// src/foods.js
import { createFood } from './schema.js';

export const FOOD_DATABASE = {
    chicken: createFood({
        id: 'chicken',
        displayName: 'Chicken Breast (Cooked)',
        aliases: ['chicken', 'chicken breast', 'poultry'],
        general: { Calories: 165, Water: 65, Ash: 1.0 },
        lipids: {
            'Total Fat': 3.6,
            'Saturated Fat': 1.01,
            'Myristic Acid (C14:0)': 0.03,
            'Palmitic Acid (C16:0)': 0.72,
            'Stearic Acid (C18:0)': 0.26,
            'Monounsaturated Fat': 1.15,
            'Oleic Acid (C18:1)': 1.1,
            'Palmitoleic Acid (C16:1)': 0.05,
            'Polyunsaturated Fat': 0.82,
            'Trans Fat': 0.02,
            Cholesterol: 85,
            Phosphatidylcholine: 65,
            Phosphatidylserine: 8,
            Phosphatidylethanolamine: 22,
            Sphingomyelin: 14,
            Plasmalogens: 4,
            'Omega-3 Total': 0.03,
            ALA: 0.01,
            EPA: 0.01,
            DHA: 0.01,
            'Omega-6 Total': 0.7,
            LA: 0.58,
            AA: 0.12
        },
        proteins_and_aminos: {
            'Total Protein': 31,
            Tryptophan: 0.34,
            Threonine: 1.29,
            Isoleucine: 1.48,
            Leucine: 2.37,
            Lysine: 2.62,
            Methionine: 0.81,
            Cystine: 0.38,
            Phenylalanine: 1.21,
            Tyrosine: 1.05,
            Valine: 1.51,
            Histidine: 0.93,
            Alanine: 1.83,
            Arginine: 2.05,
            'Aspartic Acid': 2.84,
            'Glutamic Acid': 4.8,
            Glycine: 1.63,
            Proline: 1.22,
            Serine: 1.24,
            Glutamine: 1.5,
            Taurine: 0.15
        },
        nucleic_acids_and_purines: { 'Total Purines': 115, RNA: 140, DNA: 45 },
        vitamins: {
            'Vitamin A Total': 16,
            Retinol: 16,
            'Vitamin B1 (Thiamine)': 0.07,
            'Vitamin B2 (Riboflavin)': 0.12,
            'Vitamin B3 (Niacin)': 8.5,
            'Vitamin B5 (Pantothenic Acid)': 0.9,
            'Vitamin B6': 0.4,
            'Vitamin B7 (Biotin)': 1.9,
            'Vitamin B9 (Folate DFE)': 4,
            'Vitamin B12': 0.3,
            'Vitamin D Total': 0.1,
            'Vitamin D3 (Cholecalciferol)': 0.1,
            'Vitamin E Total': 0.2,
            'Alpha-Tocopherol': 0.2,
            'Vitamin K2 (MK-4)': 1.1,
            Choline: 85,
            Betaine: 10
        },
        minerals: {
            Calcium: 15,
            Iron: 1.0,
            Magnesium: 23,
            Phosphorus: 228,
            Potassium: 256,
            Sodium: 74,
            Zinc: 1.0,
            Copper: 0.05,
            Manganese: 0.02,
            Selenium: 22.8,
            Iodine: 4,
            Chromium: 2,
            Molybdenum: 1.5,
            Fluoride: 25,
            Boron: 0.1,
            Silicon: 0.2,
            Sulfur: 240,
            Chloride: 55,
            Lithium: 0.5,
            Vanadium: 0.2,
            Cobalt: 0.8,
            Strontium: 0.1,
            Nickel: 1.2,
            Germanium: 0.02,
            Rubidium: 0.4,
            Tin: 0.01
        },
        cellular_bioactives: {
            'Coenzyme Q10': 1.5,
            'Nicotinamide Riboside (NR)': 0.2,
            'Pyrroloquinoline Quinone (PQQ)': 0.05,
            'Inositol (B8)': 12,
            PABA: 0.01,
            'Dietary Nitrate': 1.2,
            Ergothioneine: 0.1,
            Spermidine: 0.02
        },
        antioxidants: {
            Glutathione: 14.0,
            Melatonin: 0.02
        },
        absorption: {
            'Total Protein': 0.95,
            Iron: 0.25, // Heme iron high bioavailability
            Zinc: 0.35,
            Calcium: 0.3,
            'Vitamin A Total': 0.74,
            Retinol: 0.74,
            'Vitamin B1 (Thiamine)': 0.82,
            'Vitamin B2 (Riboflavin)': 0.61,
            'Vitamin B3 (Niacin)': 0.67,
            'Vitamin B6': 0.83,
            'Vitamin B7 (Biotin)': 0.89,
            'Vitamin B9 (Folate DFE)': 0.67,
            'Vitamin B12': 0.65
        }
    }),

    potato: createFood({
        id: 'potato',
        displayName: 'Russet Potato (Boiled)',
        aliases: ['potato', 'potatoes', 'russet potato'],
        general: { Calories: 77, Water: 79, Ash: 1.1 },
        organic_acids: {
            'Citric Acid': 320,
            'Malic Acid': 90,
            'Succinic Acid': 12,
            'Salicylic Acid': 0.1
        },
        carbohydrates: {
            'Total Carbohydrates': 17,
            'Soluble Fiber': 0.8,
            Pectin: 0.4,
            'Insoluble Fiber': 1.4,
            Starch: 15.0,
            'Resistant Starch': 1.2,
            'Total Sugars': 0.8,
            Sucrose: 0.3,
            Glucose: 0.2,
            Fructose: 0.3,
            'D-Mannose': 0.05
        },
        lipids: {
            'Total Fat': 0.1,
            'Saturated Fat': 0.03,
            'Palmitic Acid (C16:0)': 0.02,
            'Stearic Acid (C18:0)': 0.01,
            'Monounsaturated Fat': 0.01,
            'Oleic Acid (C18:1)': 0.01,
            'Polyunsaturated Fat': 0.04,
            Phytosterols: 8,
            'Beta-Sitosterol': 5,
            Campesterol: 2,
            Stigmasterol: 1,
            Phosphatidylcholine: 1.5,
            Phosphatidylserine: 0.2,
            Phosphatidylethanolamine: 0.5,
            'Omega-3 Total': 0.01,
            ALA: 0.01,
            'Omega-6 Total': 0.03,
            LA: 0.03
        },
        proteins_and_aminos: {
            'Total Protein': 2,
            Tryptophan: 0.03,
            Threonine: 0.07,
            Isoleucine: 0.08,
            Leucine: 0.12,
            Lysine: 0.11,
            Methionine: 0.03,
            Cystine: 0.03,
            Phenylalanine: 0.09,
            Tyrosine: 0.06,
            Valine: 0.11,
            Histidine: 0.04,
            Alanine: 0.07,
            Arginine: 0.11,
            'Aspartic Acid': 0.52,
            'Glutamic Acid': 0.34,
            Glycine: 0.06,
            Proline: 0.07,
            Serine: 0.09,
            Glutamine: 0.1
        },
        biogenic_amines: {
            Histamine: 0.1,
            Tyramine: 0.05
        },
        nucleic_acids_and_purines: { 'Total Purines': 16, RNA: 28, DNA: 6 },
        vitamins: {
            'Vitamin A Total': 1,
            'Beta-Carotene': 1,
            'Lutein & Zeaxanthin': 8,
            'Vitamin B1 (Thiamine)': 0.08,
            'Vitamin B2 (Riboflavin)': 0.03,
            'Vitamin B3 (Niacin)': 1.1,
            'Vitamin B5 (Pantothenic Acid)': 0.3,
            'Vitamin B6': 0.3,
            'Vitamin B7 (Biotin)': 0.1,
            'Vitamin B9 (Folate DFE)': 16,
            'Vitamin C': 19.7,
            'Vitamin E Total': 0.01,
            'Alpha-Tocopherol': 0.01,
            'Vitamin K1': 1.9,
            'Vitamin U (S-Methylmethionine)': 0.2,
            Choline: 12.1,
            Betaine: 0.1
        },
        minerals: {
            Calcium: 12,
            Iron: 0.8,
            Magnesium: 23,
            Phosphorus: 57,
            Potassium: 421,
            Sodium: 6,
            Zinc: 0.3,
            Copper: 0.11,
            Manganese: 0.15,
            Selenium: 0.3,
            Iodine: 1,
            Chromium: 1,
            Molybdenum: 0.8,
            Fluoride: 15,
            Boron: 0.5,
            Silicon: 2.1,
            Lithium: 1.2,
            Vanadium: 0.1,
            Cobalt: 0.05,
            Sulfur: 14,
            Chloride: 38,
            Strontium: 0.4,
            Nickel: 0.5,
            Germanium: 0.01,
            Rubidium: 2.4,
            Tin: 0.01
        },
        cellular_bioactives: {
            'Coenzyme Q10': 0.05,
            'Pyrroloquinoline Quinone (PQQ)': 0.01,
            'Inositol (B8)': 28,
            'Dietary Nitrate': 4.5,
            Ergothioneine: 0.05,
            Spermidine: 0.11
        },
        myconutrients_and_adaptogens: { 'Hericenones & Erinacines': 0.2 },
        bioactive_enzymes: { Papain: 1.5 },
        antinutrients: {
            'Phytic Acid': 18,
            'Oxalic Acid': 15,
            Lectins: 2,
            Tannins: 5,
            Saponins: 4,
            'Trypsin Inhibitors': 1
        },
        antioxidants: {
            'Total Polyphenols': 12,
            'Total Flavonoids': 3.5,
            Quercetin: 1.2,
            Glutathione: 4.5,
            Apigenin: 0.02,
            Lignans: 0.05,
            'Chlorogenic Acid': 3.8,
            Melatonin: 0.05
        },
        absorption: {
            'Total Protein': 0.75,
            Iron: 0.08, // Non-heme iron bound by plant matrix has lower uptake
            Calcium: 0.05,
            Zinc: 0.15,
            'Vitamin B3 (Niacin)': 0.4,
            'Vitamin B5 (Pantothenic Acid)': 0.6,
            'Vitamin B7 (Biotin)': 0.5,
            'Vitamin B9 (Folate DFE)': 0.5
        }
    })
};
