// src/schema.js

export const RDA_TARGETS = {
    general: { Calories: 2000, Water: 2500, Alcohol: 0, Caffeine: 100, Theobromine: 200, Ash: 10 },
    organic_acids: {
        'Citric Acid': 500,
        'Malic Acid': 300,
        'Lactic Acid': 500,
        'Acetic Acid': 200,
        'Succinic Acid': 50,
        'Salicylic Acid': 5
    },
    carbohydrates: {
        'Total Carbohydrates': 275,
        'Soluble Fiber': 8,
        'Beta-Glucan': 3,
        Pectin: 2,
        Inulin: 4,
        FOS: 2,
        GOS: 2,
        'Insoluble Fiber': 20,
        Starch: 150,
        'Resistant Starch': 5,
        'Total Sugars': 50,
        Sucrose: 10,
        Glucose: 10,
        Fructose: 10,
        Lactose: 10,
        Maltose: 5,
        Galactose: 5,
        Trehalose: 5,
        'D-Mannose': 5,
        'Total Sugar Alcohols': 10,
        Erythritol: 5,
        Xylitol: 5,
        Sorbitol: 5,
        Mannitol: 5,
        Maltitol: 5
    },
    lipids: {
        'Total Fat': 78,
        'Saturated Fat': 20,
        'Butyric Acid (C4:0)': 1000,
        'Caproic Acid (C6:0)': 100,
        'Caprylic Acid (C8:0)': 500,
        'Capric Acid (C10:0)': 500,
        'Lauric Acid (C12:0)': 1000,
        'Myristic Acid (C14:0)': 300,
        'Pentadecanoic Acid (C15:0)': 100,
        'Palmitic Acid (C16:0)': 1000,
        'Stearic Acid (C18:0)': 500,
        'Arachidic Acid (C20:0)': 100,
        'Behenic Acid (C22:0)': 100,
        'Lignoceric Acid (C24:0)': 100,
        'Monounsaturated Fat': 30,
        'Oleic Acid (C18:1)': 25,
        'Palmitoleic Acid (C16:1)': 2,
        'Vaccenic Acid (C18:1)': 1,
        'Polyunsaturated Fat': 17,
        'Conjugated Linoleic Acid (CLA)': 1500,
        'Trans Fat': 2,
        Cholesterol: 300,
        Phytosterols: 2000,
        'Beta-Sitosterol': 1000,
        Campesterol: 400,
        Stigmasterol: 200,
        Phosphatidylcholine: 500,
        Phosphatidylserine: 100,
        Phosphatidylethanolamine: 200,
        Sphingomyelin: 100,
        Plasmalogens: 20,
        'Omega-3 Total': 1.6,
        ALA: 1.6,
        EPA: 0.25,
        DHA: 0.25,
        DPA: 0.05,
        SDA: 0.1,
        ETA: 0.1,
        'Omega-6 Total': 17,
        LA: 17,
        GLA: 0.1,
        AA: 0.5,
        DGLA: 0.15
    },
    proteins_and_aminos: {
        'Total Protein': 56,
        Tryptophan: 0.28,
        Threonine: 1.05,
        Isoleucine: 1.4,
        Leucine: 2.73,
        Lysine: 2.1,
        Methionine: 1.05,
        Cystine: 1.05,
        Phenylalanine: 1.75,
        Tyrosine: 1.75,
        Valine: 1.82,
        Histidine: 0.7,
        Alanine: 3.5,
        Arginine: 4.5,
        'Aspartic Acid': 6.0,
        'Glutamic Acid': 10.0,
        Glycine: 4.0,
        Proline: 4.0,
        Serine: 4.0,
        Glutamine: 5.0,
        Taurine: 1.0,
        Citrulline: 3000,
        Ornithine: 500,
        'Beta-Alanine': 1600
    },
    biogenic_amines: { Histamine: 5, Tyramine: 10, Phenylethylamine: 2 },
    nucleic_acids_and_purines: { 'Total Purines': 400, RNA: 1000, DNA: 300 },
    vitamins: {
        'Vitamin A Total': 900,
        Retinol: 900,
        'Beta-Carotene': 5000,
        'Alpha-Carotene': 1000,
        'Beta-Cryptoxanthin': 1000,
        'Lutein & Zeaxanthin': 12000,
        Lycopene: 10000,
        'Vitamin B1 (Thiamine)': 1.2,
        'Vitamin B2 (Riboflavin)': 1.3,
        'Vitamin B3 (Niacin)': 16,
        'Vitamin B5 (Pantothenic Acid)': 5,
        'Vitamin B6': 1.3,
        'Vitamin B7 (Biotin)': 30,
        'Vitamin B9 (Folate DFE)': 400,
        'Vitamin B12': 2.4,
        'Vitamin C': 90,
        'Vitamin D Total': 15,
        'Vitamin D2 (Ergocalciferol)': 5,
        'Vitamin D3 (Cholecalciferol)': 10,
        'Vitamin E Total': 15,
        'Alpha-Tocopherol': 15,
        'Beta-Tocopherol': 2,
        'Gamma-Tocopherol': 5,
        'Delta-Tocopherol': 2,
        'Alpha-Tocotrienol': 2,
        'Beta-Tocotrienol': 1,
        'Gamma-Tocotrienol': 2,
        'Delta-Tocotrienol': 1,
        'Vitamin K1': 120,
        'Vitamin K2 (MK-4)': 100,
        'Vitamin K2 (MK-7)': 50,
        'Vitamin K2 (MK-9)': 30,
        'Vitamin U (S-Methylmethionine)': 50,
        Choline: 550,
        Betaine: 100
    },
    minerals: {
        Calcium: 1000,
        Iron: 8,
        Magnesium: 400,
        Phosphorus: 700,
        Potassium: 3400,
        Sodium: 2300,
        Zinc: 11,
        Copper: 0.9,
        Manganese: 2.3,
        Selenium: 55,
        Iodine: 150,
        Chromium: 35,
        Molybdenum: 45,
        Fluoride: 4000,
        Boron: 3,
        Silicon: 30,
        Sulfur: 1000,
        Chloride: 2300,
        Lithium: 1000,
        Vanadium: 10,
        Cobalt: 5,
        Strontium: 5,
        Nickel: 100,
        Germanium: 5,
        Rubidium: 1000,
        Tin: 10
    },
    cellular_bioactives: {
        'Coenzyme Q10': 100,
        'Nicotinamide Riboside (NR)': 250,
        'Pyrroloquinoline Quinone (PQQ)': 20,
        'Inositol (B8)': 1000,
        PABA: 50,
        'Dietary Nitrate': 150,
        Ergothioneine: 10,
        Spermidine: 12,
        'L-Theanine': 100,
        'Urolithin A': 250
    },
    myconutrients_and_adaptogens: {
        'Hericenones & Erinacines': 50,
        Cordycepin: 10,
        Withanolides: 20,
        'Salidroside & Rosavin': 15,
        Bacosides: 150
    },
    bioactive_enzymes: { Bromelain: 100, Papain: 100 },
    antinutrients: {
        'Phytic Acid': 1000,
        'Oxalic Acid': 200,
        Lectins: 10,
        Goitrogens: 5,
        Tannins: 100,
        Saponins: 50,
        'Trypsin Inhibitors': 5
    },
    antioxidants: {
        'Total Polyphenols': 500,
        'Total Flavonoids': 200,
        Anthocyanins: 50,
        Quercetin: 50,
        Resveratrol: 20,
        Glutathione: 100,
        Astaxanthin: 4,
        EGCG: 200,
        Curcumin: 200,
        Apigenin: 50,
        Fisetin: 100,
        Lignans: 50,
        Pterostilbene: 50,
        'Ursolic Acid': 100,
        'Chlorogenic Acid': 100,
        Allicin: 10,
        Sulforaphane: 15,
        Melatonin: 5,
        Capsaicin: 5,
        DIM: 100,
        Kaempferol: 50,
        Glucoraphanin: 10
    }
};

export const UL_TARGETS = {
    general: { Calories: 3500, Water: 5000, Caffeine: 400, Theobromine: 800 },
    lipids: { 'Saturated Fat': 40, 'Trans Fat': 3, Cholesterol: 500, 'Omega-6 Total': 30 },
    vitamins: {
        'Vitamin A Total': 3000,
        Retinol: 3000,
        'Vitamin B3 (Niacin)': 35,
        'Vitamin B6': 100,
        'Vitamin D Total': 100,
        'Vitamin E Total': 1000,
        Choline: 3500
    },
    minerals: {
        Calcium: 2500,
        Iron: 45,
        Magnesium: 350,
        Potassium: 5000,
        Sodium: 2300,
        Zinc: 40,
        Copper: 10,
        Manganese: 11,
        Selenium: 400,
        Iodine: 1100,
        Fluoride: 10000
    },
    antinutrients: { 'Phytic Acid': 1500, 'Oxalic Acid': 500 }
};

export const NUTRIENT_UNITS = {
    general: {
        Calories: { unit: 'kcal', defaultAbsorb: 0.95 },
        Water: { unit: 'g', defaultAbsorb: 0.99 },
        Alcohol: { unit: 'g', defaultAbsorb: 1.0 },
        Caffeine: { unit: 'mg', defaultAbsorb: 0.99 },
        Theobromine: { unit: 'mg', defaultAbsorb: 0.99 },
        Ash: { unit: 'g', defaultAbsorb: 0.0 }
    },
    organic_acids: {
        'Citric Acid': { unit: 'mg', defaultAbsorb: 0.9 },
        'Malic Acid': { unit: 'mg', defaultAbsorb: 0.9 },
        'Lactic Acid': { unit: 'mg', defaultAbsorb: 0.95 },
        'Acetic Acid': { unit: 'mg', defaultAbsorb: 0.95 },
        'Succinic Acid': { unit: 'mg', defaultAbsorb: 0.9 },
        'Salicylic Acid': { unit: 'mg', defaultAbsorb: 0.85 }
    },
    carbohydrates: {
        'Total Carbohydrates': { unit: 'g', defaultAbsorb: 0.95 },
        'Soluble Fiber': { unit: 'g', indent: 1, defaultAbsorb: 0.0 },
        'Beta-Glucan': { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        Pectin: { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        Inulin: { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        FOS: { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        GOS: { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        'Insoluble Fiber': { unit: 'g', indent: 1, defaultAbsorb: 0.0 },
        Starch: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        'Resistant Starch': { unit: 'g', indent: 2, defaultAbsorb: 0.0 },
        'Total Sugars': { unit: 'g', indent: 1, defaultAbsorb: 0.98 },
        Sucrose: { unit: 'g', indent: 2, defaultAbsorb: 0.98 },
        Glucose: { unit: 'g', indent: 2, defaultAbsorb: 0.99 },
        Fructose: { unit: 'g', indent: 2, defaultAbsorb: 0.95 },
        Lactose: { unit: 'g', indent: 2, defaultAbsorb: 0.95 },
        Maltose: { unit: 'g', indent: 2, defaultAbsorb: 0.98 },
        Galactose: { unit: 'g', indent: 2, defaultAbsorb: 0.98 },
        Trehalose: { unit: 'g', indent: 2, defaultAbsorb: 0.9 },
        'D-Mannose': { unit: 'g', indent: 2, defaultAbsorb: 0.9 },
        'Total Sugar Alcohols': { unit: 'g', indent: 1, defaultAbsorb: 0.5 },
        Erythritol: { unit: 'g', indent: 2, defaultAbsorb: 0.9 },
        Xylitol: { unit: 'g', indent: 2, defaultAbsorb: 0.5 },
        Sorbitol: { unit: 'g', indent: 2, defaultAbsorb: 0.5 },
        Mannitol: { unit: 'g', indent: 2, defaultAbsorb: 0.25 },
        Maltitol: { unit: 'g', indent: 2, defaultAbsorb: 0.5 }
    },
    lipids: {
        'Total Fat': { unit: 'g', defaultAbsorb: 0.95 },
        'Saturated Fat': { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        'Butyric Acid (C4:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Caproic Acid (C6:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Caprylic Acid (C8:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Capric Acid (C10:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Lauric Acid (C12:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Myristic Acid (C14:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Pentadecanoic Acid (C15:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Palmitic Acid (C16:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Stearic Acid (C18:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Arachidic Acid (C20:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Behenic Acid (C22:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Lignoceric Acid (C24:0)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Monounsaturated Fat': { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        'Oleic Acid (C18:1)': { unit: 'g', indent: 2, defaultAbsorb: 0.95 },
        'Palmitoleic Acid (C16:1)': { unit: 'g', indent: 2, defaultAbsorb: 0.95 },
        'Vaccenic Acid (C18:1)': { unit: 'g', indent: 2, defaultAbsorb: 0.95 },
        'Polyunsaturated Fat': { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        'Conjugated Linoleic Acid (CLA)': { unit: 'mg', indent: 2, defaultAbsorb: 0.95 },
        'Trans Fat': { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        Cholesterol: { unit: 'mg', defaultAbsorb: 0.5 },
        Phytosterols: { unit: 'mg', defaultAbsorb: 0.05 },
        'Beta-Sitosterol': { unit: 'mg', indent: 1, defaultAbsorb: 0.05 },
        Campesterol: { unit: 'mg', indent: 1, defaultAbsorb: 0.05 },
        Stigmasterol: { unit: 'mg', indent: 1, defaultAbsorb: 0.05 },
        Phosphatidylcholine: { unit: 'mg', indent: 1, defaultAbsorb: 0.85 },
        Phosphatidylethanolamine: { unit: 'mg', indent: 1, defaultAbsorb: 0.85 },
        Phosphatidylserine: { unit: 'mg', indent: 1, defaultAbsorb: 0.85 },
        Sphingomyelin: { unit: 'mg', indent: 1, defaultAbsorb: 0.8 },
        Plasmalogens: { unit: 'mg', indent: 1, defaultAbsorb: 0.8 },
        'Omega-3 Total': { unit: 'g', defaultAbsorb: 0.95 },
        ALA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        EPA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        DHA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        DPA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        SDA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        ETA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        'Omega-6 Total': { unit: 'g', defaultAbsorb: 0.95 },
        LA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        GLA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        AA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 },
        DGLA: { unit: 'g', indent: 1, defaultAbsorb: 0.95 }
    },
    proteins_and_aminos: {
        'Total Protein': { unit: 'g', defaultAbsorb: 0.9 },
        essential_subheader: { isSubheader: true, label: 'Essential Amino Acids' },
        Tryptophan: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Threonine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Isoleucine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Leucine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Lysine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Methionine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Cystine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Phenylalanine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Tyrosine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Valine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Histidine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        non_essential_subheader: { isSubheader: true, label: 'Non-Essential Amino Acids' },
        Alanine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Arginine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        'Aspartic Acid': { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        'Glutamic Acid': { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Glycine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Proline: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Serine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Glutamine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Taurine: { unit: 'g', indent: 1, defaultAbsorb: 0.9 },
        Citrulline: { unit: 'mg', indent: 1, defaultAbsorb: 0.9 },
        Ornithine: { unit: 'mg', indent: 1, defaultAbsorb: 0.9 },
        'Beta-Alanine': { unit: 'mg', indent: 1, defaultAbsorb: 0.9 }
    },
    biogenic_amines: {
        Histamine: { unit: 'mg', defaultAbsorb: 0.85 },
        Tyramine: { unit: 'mg', defaultAbsorb: 0.85 },
        Phenylethylamine: { unit: 'mg', defaultAbsorb: 0.85 }
    },
    nucleic_acids_and_purines: {
        'Total Purines': { unit: 'mg', defaultAbsorb: 0.8 },
        RNA: { unit: 'mg', defaultAbsorb: 0.8 },
        DNA: { unit: 'mg', defaultAbsorb: 0.8 }
    },
    vitamins: {
        'Vitamin A Total': { unit: 'mcg', defaultAbsorb: 0.7 },
        Retinol: { unit: 'mcg', indent: 1, defaultAbsorb: 0.75 },
        'Alpha-Carotene': { unit: 'mcg', indent: 1, defaultAbsorb: 0.15 },
        'Beta-Carotene': { unit: 'mcg', indent: 1, defaultAbsorb: 0.15 },
        'Beta-Cryptoxanthin': { unit: 'mcg', indent: 1, defaultAbsorb: 0.15 },
        'Lutein & Zeaxanthin': { unit: 'mcg', indent: 1, defaultAbsorb: 0.15 },
        Lycopene: { unit: 'mcg', indent: 1, defaultAbsorb: 0.15 },
        'Vitamin B1 (Thiamine)': { unit: 'mg', defaultAbsorb: 0.8 },
        'Vitamin B2 (Riboflavin)': { unit: 'mg', defaultAbsorb: 0.65 },
        'Vitamin B3 (Niacin)': { unit: 'mg', defaultAbsorb: 0.65 },
        'Vitamin B5 (Pantothenic Acid)': { unit: 'mg', defaultAbsorb: 0.75 },
        'Vitamin B6': { unit: 'mg', defaultAbsorb: 0.8 },
        'Vitamin B7 (Biotin)': { unit: 'mcg', defaultAbsorb: 0.75 },
        'Vitamin B9 (Folate DFE)': { unit: 'mcg', defaultAbsorb: 0.6 },
        'Vitamin B12': { unit: 'mcg', defaultAbsorb: 0.65 },
        'Vitamin C': { unit: 'mg', defaultAbsorb: 0.8 },
        'Vitamin D Total': { unit: 'mcg', defaultAbsorb: 0.7 },
        'Vitamin D2 (Ergocalciferol)': { unit: 'mcg', indent: 1, defaultAbsorb: 0.65 },
        'Vitamin D3 (Cholecalciferol)': { unit: 'mcg', indent: 1, defaultAbsorb: 0.7 },
        'Vitamin E Total': { unit: 'mg', defaultAbsorb: 0.6 },
        'Alpha-Tocopherol': { unit: 'mg', indent: 1, defaultAbsorb: 0.6 },
        'Beta-Tocopherol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Gamma-Tocopherol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Delta-Tocopherol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Alpha-Tocotrienol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Beta-Tocotrienol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Gamma-Tocotrienol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Delta-Tocotrienol': { unit: 'mg', indent: 1, defaultAbsorb: 0.5 },
        'Vitamin K1': { unit: 'mcg', defaultAbsorb: 0.2 },
        'Vitamin K2 (MK-4)': { unit: 'mcg', defaultAbsorb: 0.6 },
        'Vitamin K2 (MK-7)': { unit: 'mcg', defaultAbsorb: 0.65 },
        'Vitamin K2 (MK-9)': { unit: 'mcg', defaultAbsorb: 0.6 },
        'Vitamin U (S-Methylmethionine)': { unit: 'mg', defaultAbsorb: 0.7 },
        Choline: { unit: 'mg', defaultAbsorb: 0.8 },
        Betaine: { unit: 'mg', defaultAbsorb: 0.8 }
    },
    minerals: {
        Calcium: { unit: 'mg', defaultAbsorb: 0.3 },
        Iron: { unit: 'mg', defaultAbsorb: 0.15 },
        Magnesium: { unit: 'mg', defaultAbsorb: 0.35 },
        Phosphorus: { unit: 'mg', defaultAbsorb: 0.6 },
        Potassium: { unit: 'mg', defaultAbsorb: 0.9 },
        Sodium: { unit: 'mg', defaultAbsorb: 0.95 },
        Zinc: { unit: 'mg', defaultAbsorb: 0.3 },
        Copper: { unit: 'mg', defaultAbsorb: 0.35 },
        Manganese: { unit: 'mg', defaultAbsorb: 0.05 },
        Selenium: { unit: 'mcg', defaultAbsorb: 0.8 },
        Iodine: { unit: 'mcg', defaultAbsorb: 0.9 },
        Chromium: { unit: 'mcg', defaultAbsorb: 0.02 },
        Molybdenum: { unit: 'mcg', defaultAbsorb: 0.75 },
        Fluoride: { unit: 'mcg', defaultAbsorb: 0.8 },
        Boron: { unit: 'mg', defaultAbsorb: 0.8 },
        Silicon: { unit: 'mg', defaultAbsorb: 0.25 },
        Sulfur: { unit: 'mg', defaultAbsorb: 0.6 },
        Chloride: { unit: 'mg', defaultAbsorb: 0.95 },
        Lithium: { unit: 'mcg', defaultAbsorb: 0.8 },
        Vanadium: { unit: 'mcg', defaultAbsorb: 0.1 },
        Cobalt: { unit: 'mcg', defaultAbsorb: 0.5 },
        Strontium: { unit: 'mg', defaultAbsorb: 0.2 },
        Nickel: { unit: 'mcg', defaultAbsorb: 0.1 },
        Germanium: { unit: 'mcg', defaultAbsorb: 0.3 },
        Rubidium: { unit: 'mcg', defaultAbsorb: 0.8 },
        Tin: { unit: 'mcg', defaultAbsorb: 0.05 }
    },
    cellular_bioactives: {
        'Coenzyme Q10': { unit: 'mg', defaultAbsorb: 0.2 },
        'Nicotinamide Riboside (NR)': { unit: 'mg', defaultAbsorb: 0.5 },
        'Pyrroloquinoline Quinone (PQQ)': { unit: 'mcg', defaultAbsorb: 0.3 },
        'Inositol (B8)': { unit: 'mg', defaultAbsorb: 0.8 },
        PABA: { unit: 'mg', defaultAbsorb: 0.75 },
        'Dietary Nitrate': { unit: 'mg', defaultAbsorb: 0.9 },
        Ergothioneine: { unit: 'mg', defaultAbsorb: 0.8 },
        Spermidine: { unit: 'mg', defaultAbsorb: 0.6 },
        'L-Theanine': { unit: 'mg', defaultAbsorb: 0.85 },
        'Urolithin A': { unit: 'mg', defaultAbsorb: 0.3 },
        'Alpha-Lipoic Acid (ALA-Antioxidant)': { unit: 'mg', defaultAbsorb: 0.35 }
    },
    myconutrients_and_adaptogens: {
        'Hericenones & Erinacines': { unit: 'mg', defaultAbsorb: 0.5 },
        Cordycepin: { unit: 'mg', defaultAbsorb: 0.5 },
        Withanolides: { unit: 'mg', defaultAbsorb: 0.5 },
        'Salidroside & Rosavin': { unit: 'mg', defaultAbsorb: 0.5 },
        Bacosides: { unit: 'mg', defaultAbsorb: 0.5 }
    },
    bioactive_enzymes: {
        Bromelain: { unit: 'mg', defaultAbsorb: 0.4 },
        Papain: { unit: 'mg', defaultAbsorb: 0.4 }
    },
    antinutrients: {
        'Phytic Acid': { unit: 'mg', defaultAbsorb: 0.1 },
        'Oxalic Acid': { unit: 'mg', defaultAbsorb: 0.1 },
        Lectins: { unit: 'unit', defaultAbsorb: 0.05 },
        Goitrogens: { unit: 'unit', defaultAbsorb: 0.2 },
        Tannins: { unit: 'mg', defaultAbsorb: 0.1 },
        Saponins: { unit: 'mg', defaultAbsorb: 0.05 },
        'Trypsin Inhibitors': { unit: 'unit', defaultAbsorb: 0.05 }
    },
    antioxidants: {
        'Total Polyphenols': { unit: 'mg', defaultAbsorb: 0.3 },
        'Total Flavonoids': { unit: 'mg', defaultAbsorb: 0.25 },
        Anthocyanins: { unit: 'mg', defaultAbsorb: 0.2 },
        Quercetin: { unit: 'mg', defaultAbsorb: 0.2 },
        Resveratrol: { unit: 'mg', defaultAbsorb: 0.2 },
        Glutathione: { unit: 'mg', defaultAbsorb: 0.15 },
        Astaxanthin: { unit: 'mg', defaultAbsorb: 0.3 },
        EGCG: { unit: 'mg', defaultAbsorb: 0.2 },
        Curcumin: { unit: 'mg', defaultAbsorb: 0.05 },
        Apigenin: { unit: 'mg', defaultAbsorb: 0.3 },
        Fisetin: { unit: 'mg', defaultAbsorb: 0.3 },
        Lignans: { unit: 'mg', defaultAbsorb: 0.25 },
        Pterostilbene: { unit: 'mg', defaultAbsorb: 0.4 },
        'Ursolic Acid': { unit: 'mg', defaultAbsorb: 0.1 },
        'Chlorogenic Acid': { unit: 'mg', defaultAbsorb: 0.35 },
        Allicin: { unit: 'mg', defaultAbsorb: 0.6 },
        Sulforaphane: { unit: 'mg', defaultAbsorb: 0.7 },
        Melatonin: { unit: 'mcg', defaultAbsorb: 0.5 },
        Capsaicin: { unit: 'mg', defaultAbsorb: 0.8 },
        DIM: { unit: 'mg', defaultAbsorb: 0.4 },
        Kaempferol: { unit: 'mg', defaultAbsorb: 0.2 },
        Glucoraphanin: { unit: 'mg', defaultAbsorb: 0.4 }
    }
};

/**
 * Hydrates a sparse food profile into the full schema.
 * All omitted nutrients default cleanly to 0.
 * Custom absorption rates override the biological default.
 */
export function createFood(sparseFood) {
    const fullProfile = {
        id: sparseFood.id,
        displayName: sparseFood.displayName,
        aliases: sparseFood.aliases || [sparseFood.id],
        insights: sparseFood.insights || null,
        absorption: {}
    };

    for (const [category, compounds] of Object.entries(NUTRIENT_UNITS)) {
        fullProfile[category] = {};
        for (const [compoundName, meta] of Object.entries(compounds)) {
            if (meta.isSubheader) continue;

            // Ingest value or default to 0
            fullProfile[category][compoundName] = sparseFood[category]?.[compoundName] ?? 0;

            // Ingest custom food-specific absorption rate or fallback to schema default
            const customRate = sparseFood.absorption?.[compoundName];
            fullProfile.absorption[compoundName] = customRate !== undefined ? customRate : (meta.defaultAbsorb ?? 1.0);
        }
    }

    return fullProfile;
}
